// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHkW9awm73Qwo_OODN_AEfywBplX2JRMM',
    appId: '1:388092997037:web:3d38ae2d5f3e05d6870524',
    messagingSenderId: '388092997037',
    projectId: 'flutter-firebase-app-9afc3',
    authDomain: 'flutter-firebase-app-9afc3.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-9afc3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBATohBEaij8qlWMZ95Zlxf_Xn_YfAaG_0',
    appId: '1:388092997037:android:f5fb125a9c209ab8870524',
    messagingSenderId: '388092997037',
    projectId: 'flutter-firebase-app-9afc3',
    storageBucket: 'flutter-firebase-app-9afc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBGI-yRLOmrB4pu-STvNMRJWDXDLH812Y',
    appId: '1:388092997037:ios:65a4faa774748d2d870524',
    messagingSenderId: '388092997037',
    projectId: 'flutter-firebase-app-9afc3',
    storageBucket: 'flutter-firebase-app-9afc3.firebasestorage.app',
    iosBundleId: 'br.com.amandacornelsen.passwordsecurity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBGI-yRLOmrB4pu-STvNMRJWDXDLH812Y',
    appId: '1:388092997037:ios:65a4faa774748d2d870524',
    messagingSenderId: '388092997037',
    projectId: 'flutter-firebase-app-9afc3',
    storageBucket: 'flutter-firebase-app-9afc3.firebasestorage.app',
    iosBundleId: 'br.com.amandacornelsen.passwordsecurity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHkW9awm73Qwo_OODN_AEfywBplX2JRMM',
    appId: '1:388092997037:web:6de64088b07c1590870524',
    messagingSenderId: '388092997037',
    projectId: 'flutter-firebase-app-9afc3',
    authDomain: 'flutter-firebase-app-9afc3.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-9afc3.firebasestorage.app',
  );
}
